import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    "header.product": "Product",
    "header.features": "Features",
    "header.cases": "Case Studies",
    "header.contact": "Contact",
    "header.cta": "Request a Demo",
    
    // Hero
    "hero.title": "Transform Your Customer Service with AI",
    "hero.subtitle": "Automate your phone calls with an ultra-realistic AI that handles your customer requests 24/7",
    "hero.cta": "Try for Free",
    "hero.demo": "See Interactive Demo",
    "hero.badge1": "48h Deployment",
    "hero.badge2": "Reliable 24/7",
    "hero.badge3": "100% Customizable",
    "hero.activeCall": "Active AI Call",
    "hero.accuracy": "97% accuracy • Real-time",
    
    // Product
    "product.title": "A Complete Solution for Your Customer Service",
    "product.subtitle": "Our conversational AI integrates perfectly with your existing systems",
    "product.feature1.title": "Intelligent Automatic Response",
    "product.feature1.description": "Your customers get instant, natural and contextualized answers at any time.",
    "product.feature2.title": "Inbound & Outbound Calls",
    "product.feature2.description": "Handle call reception and launch proactive campaigns with the same intelligence.",
    "product.feature3.title": "Business Integration",
    "product.feature3.description": "Connected to your CRM tools, calendar and business systems for a seamless experience.",
    "product.discover": "Discover",
    
    // Features
    "features.title": "Advanced Features",
    "features.subtitle": "Cutting-edge technology for exceptional customer experience",
    "features.feature1.title": "Advanced Speech Recognition (ASR)",
    "features.feature1.description": "Real-time transcription with business accuracy and advanced contextual understanding",
    "features.feature1.stat": "-30%",
    "features.feature1.label": "wait time",
    "features.feature2.title": "Natural Voice Synthesis (TTS)",
    "features.feature2.description": "Ultra-realistic customizable voices, tone adapted to your brand and sector",
    "features.feature2.stat": "+45%",
    "features.feature2.label": "customer satisfaction",
    "features.feature3.title": "Intelligent Call Routing",
    "features.feature3.description": "Automatic transfer to the right department or agent with preserved context",
    "features.feature3.stat": "95%",
    "features.feature3.label": "first call resolution",
    "features.feature4.title": "AI Analytics and Insights",
    "features.feature4.description": "Real-time dashboards, predictive trends and recommendations",
    "features.feature4.stat": "+60%",
    "features.feature4.label": "sales performance",
    "features.feature5.title": "Intelligent Dynamic Scripts",
    "features.feature5.description": "Adapt dialogues in real time according to context and customer behavior",
    "features.feature5.stat": "48h",
    "features.feature5.label": "deployed",
    "features.badge1": "Real-time",
    "features.badge2": "Customizable",
    "features.badge3": "Scalable",
    
    // Social Proof
    "social.title": "They Trust Us",
    "social.subtitle": "Join hundreds of companies that have revolutionized their customer service",
    "social.stat1.value": "50,000+",
    "social.stat1.label": "Calls handled per month",
    "social.stat2.value": "30",
    "social.stat2.label": "Minutes saved per day",
    "social.stat3.value": "45%",
    "social.stat3.label": "Conversion rate",
    "social.testimonial1.content": "Since BerinIA, we never miss a call. +40% appointment bookings in 3 months. The AI perfectly understands the real estate context.",
    "social.testimonial1.name": "Marie Dubois",
    "social.testimonial1.role": "Sales Director",
    "social.testimonial1.company": "Immo+",
    "social.testimonial2.content": "The AI handles routine requests perfectly. My team focuses on complex cases. Positive ROI from the 2nd month.",
    "social.testimonial2.name": "Thomas Bernard",
    "social.testimonial2.role": "Manager",
    "social.testimonial2.company": "Services Pro",
    "social.testimonial3.content": "Quick installation, clear training. Customers appreciate 24/7 responsiveness. Best investment of the year.",
    "social.testimonial3.name": "Sophie Martin",
    "social.testimonial3.role": "Customer Manager",
    "social.testimonial3.company": "TechServices",
    "social.trust1.label": "Availability",
    "social.trust1.value": "99.9%",
    "social.trust2.label": "GDPR Compliant",
    "social.trust3.label": "24/7 Support",
    "social.trust4.label": "ISO Security",
    
    // FAQ
    "faq.title": "Frequently Asked Questions",
    "faq.subtitle": "Everything you need to know about BerinIA",
    "faq.q1": "How long does it take to deploy BerinIA?",
    "faq.a1": "Initial deployment takes between 48 hours and 5 days depending on the complexity of your scenarios. We handle the technical integration and AI customization for your sector.",
    "faq.q2": "Can AI really replace a human?",
    "faq.a2": "BerinIA efficiently handles common and repetitive requests (80% of calls). For complex cases, the call is intelligently transferred to a human agent with all the context.",
    "faq.q3": "How does integration with our CRM work?",
    "faq.a3": "We offer native connectors for Salesforce, HubSpot, Pipedrive and other tools. Open APIs also allow quick custom integrations.",
    "faq.q4": "What are the pricing options?",
    "faq.a4": "We offer a pay-per-use model (cost per call) or monthly plan based on your volume. Contact us for a personalized quote tailored to your specific needs.",
    "faq.q5": "Is data secure and GDPR compliant?",
    "faq.a5": "Absolutely. BerinIA is hosted in Europe, GDPR compliant, and ISO 27001 certified. Your customer data remains private, encrypted and is never shared.",
    "faq.q6": "Can we customize the AI's voice and tone?",
    "faq.a6": "Yes, completely. You choose the voice, vocabulary, level of formality and scripts according to your brand image and sector of activity. Demos available.",
    "faq.noAnswer": "Can't find the answer to your question?",
    "faq.contact": "Contact our team",
    
    // Contact
    "contact.title": "Ready to Transform Your Customer Service?",
    "contact.subtitle": "Contact us for a personalized demo",
    "contact.name": "Full Name",
    "contact.email": "Professional Email",
    "contact.phone": "Phone Number",
    "contact.company": "Company",
    "contact.message": "Your Message",
    "contact.send": "Send Request",
    "contact.success": "Message sent successfully!",
    "contact.error": "Error sending message",
    "contact.ourDetails": "Our Contact Details",
    "contact.emailLabel": "Email",
    "contact.phoneLabel": "Phone",
    "contact.hoursLabel": "Business Hours",
    "contact.schedule": "Mon - Fri: 9am - 6pm\nSat: 9am - 12pm",
    "contact.dataSecurityTitle": "Your Data is Secure",
    "contact.dataSecurityText": "We respect your privacy. No data is sold to third parties. GDPR compliance guaranteed, European hosting, end-to-end encryption.",
    
    // Footer
    "footer.product": "Product",
    "footer.features": "Features",
    "footer.pricing": "Pricing",
    "footer.company": "Company",
    "footer.about": "About Us",
    "footer.blog": "Blog",
    "footer.careers": "Careers",
    "footer.legal": "Legal",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.cookies": "Cookie Policy",
    "footer.notice": "Legal Notice",
    "footer.rights": "All rights reserved",
    
    // Test Page
    "test.title": "Try Our AI for Free",
    "test.subtitle": "Enter your information and our AI will call you immediately for a live demonstration",
    "test.phone": "Phone Number",
    "test.phonePlaceholder": "+33 6 12 34 56 78",
    "test.sector": "Business Sector",
    "test.sectorPlaceholder": "E-commerce, Real Estate, Services...",
    "test.company": "Company Name",
    "test.companyPlaceholder": "Your company",
    "test.email": "Professional Email",
    "test.emailPlaceholder": "contact@company.com",
    "test.consent": "I agree to be contacted for a product demonstration",
    "test.gdpr": "I accept the processing of my personal data in accordance with the GDPR",
    "test.terms": "I accept the general terms and conditions of use",
    "test.submit": "Start Demo Call",
    "test.submitting": "Starting call...",
    "test.success": "Success! You will receive a call in a few moments",
    "test.error": "An error occurred. Please try again.",
    "test.checkboxError": "Please accept all required conditions",
    
    // Not Found
    "notfound.title": "404",
    "notfound.message": "Oops! Page not found",
    "notfound.home": "Return to Home",
    
    // Legal Pages Common
    "legal.backHome": "Back to Home",
    "legal.lastUpdate": "Last updated:",
    
    // Legal Notice
    "legal.notice.title": "Legal Notice",
    "legal.notice.editor": "Website Publisher",
    "legal.notice.companyName": "Company name:",
    "legal.notice.legalForm": "Legal form:",
    "legal.notice.capital": "Share capital:",
    "legal.notice.headquarters": "Headquarters:",
    "legal.notice.rcs": "RCS:",
    "legal.notice.siret": "SIRET:",
    "legal.notice.vat": "VAT number:",
    "legal.notice.email": "Email:",
    "legal.notice.phone": "Phone:",
    "legal.notice.director": "Publication Director",
    "legal.notice.directorName": "[Publication director name]",
    "legal.notice.hosting": "Hosting",
    "legal.notice.hostedBy": "The website is hosted by:",
    "legal.notice.hostName": "Host name:",
    "legal.notice.hostAddress": "Address:",
    "legal.notice.hostPhone": "Phone:",
    "legal.notice.ip": "Intellectual Property",
    "legal.notice.ipText1": "This entire website is subject to French and international copyright and intellectual property law. All reproduction rights are reserved, including for downloadable documents and iconographic and photographic representations.",
    "legal.notice.ipText2": "Reproduction of all or part of this site on any electronic medium whatsoever is strictly prohibited except with the express permission of the publication director.",
    "legal.notice.gdpr": "Personal Data Protection",
    "legal.notice.gdprText1": "In accordance with the 'Informatique et Libertés' law of January 6, 1978 as amended and the General Data Protection Regulation (GDPR), you have the right to access, rectify, delete and object to personal data concerning you.",
    "legal.notice.gdprText2": "To exercise these rights, you can contact us at: contact@berinia.com",
    "legal.notice.cookies": "Cookies",
    "legal.notice.cookiesText1": "The website may request your acceptance of cookies for statistical and display purposes. A cookie is information stored on your hard drive by the server of the website you visit.",
    "legal.notice.cookiesText2": "You can disable cookies in your browser settings.",
    "legal.notice.links": "Hyperlinks",
    "legal.notice.linksText": "The website may contain hyperlinks to other sites. BerinIA exercises no control over these sites and disclaims all responsibility for their content.",
    "legal.notice.law": "Applicable Law",
    "legal.notice.lawText": "These legal notices are governed by French law. In the event of a dispute, the French courts shall have sole jurisdiction.",
    
    // Privacy Policy
    "privacy.title": "Privacy Policy",
    "privacy.intro": "Introduction",
    "privacy.introText": "BerinIA attaches great importance to the protection of your personal data. This privacy policy informs you about how we collect, use and protect your personal information in accordance with the General Data Protection Regulation (GDPR).",
    "privacy.controller": "Data Controller",
    "privacy.controllerText": "The data controller is:",
    "privacy.controllerName": "BerinIA",
    "privacy.dataCollected": "Data Collected",
    "privacy.dataCollectedText": "We collect the following personal data:",
    "privacy.dataItem1": "First and last name",
    "privacy.dataItem2": "Professional email address",
    "privacy.dataItem3": "Phone number",
    "privacy.dataItem4": "Company name",
    "privacy.dataItem5": "Messages and information you send us",
    "privacy.dataItem6": "Browsing data (cookies, IP address, browser)",
    "privacy.purposes": "Processing Purposes",
    "privacy.purposesText": "Your data is collected for the following purposes:",
    "privacy.purpose1": "Respond to your contact and demonstration requests",
    "privacy.purpose2": "Manage customer relations and after-sales service",
    "privacy.purpose3": "Improve our services and website",
    "privacy.purpose4": "Send you commercial information (with your consent)",
    "privacy.purpose5": "Comply with our legal and regulatory obligations",
    "privacy.legalBasis": "Legal Basis",
    "privacy.legalBasisText": "The processing of your data is based on:",
    "privacy.basis1": "Your explicit consent",
    "privacy.basis2": "Performance of a contract or pre-contractual measures",
    "privacy.basis3": "Our legitimate interest in improving our services",
    "privacy.basis4": "Compliance with our legal obligations",
    "privacy.recipients": "Data Recipients",
    "privacy.recipientsText1": "Your personal data is intended for BerinIA's internal services. It may also be transmitted to our technical subcontractors (hosting, email) who act solely on our instructions.",
    "privacy.recipientsText2": "Your data is never sold to third parties.",
    "privacy.retention": "Retention Period",
    "privacy.retentionText": "Your data is kept for:",
    "privacy.retention1": "3 years for prospects from the last contact",
    "privacy.retention2": "Duration of contractual relationship + 5 years for customers",
    "privacy.retention3": "Maximum 13 months for audience measurement cookies",
    "privacy.rights": "Your Rights",
    "privacy.rightsText": "In accordance with GDPR, you have the following rights:",
    "privacy.right1": "Right of access:",
    "privacy.right1Text": "obtain a copy of your data",
    "privacy.right2": "Right of rectification:",
    "privacy.right2Text": "correct your inaccurate data",
    "privacy.right3": "Right to erasure:",
    "privacy.right3Text": "delete your data",
    "privacy.right4": "Right to restriction:",
    "privacy.right4Text": "restrict the processing of your data",
    "privacy.right5": "Right to object:",
    "privacy.right5Text": "object to the processing of your data",
    "privacy.right6": "Right to portability:",
    "privacy.right6Text": "retrieve your data in a structured format",
    "privacy.rightsContact": "To exercise these rights, contact us at: contact@berinia.com",
    "privacy.security": "Security",
    "privacy.securityText1": "We implement all appropriate technical and organizational measures to protect your data against loss, misuse, unauthorized access, disclosure, alteration or destruction.",
    "privacy.securityText2": "Our servers are hosted in Europe and benefit from end-to-end encryption.",
    "privacy.cookies": "Cookies",
    "privacy.cookiesText": "Our website uses cookies to improve your browsing experience and measure audience. You can manage your cookie preferences in your browser settings.",
    "privacy.complaint": "Complaint",
    "privacy.complaintText": "If you believe your rights are not being respected, you can file a complaint with the CNIL:",
    "privacy.cnilAddress": "CNIL - 3 Place de Fontenoy - TSA 80715 - 75334 PARIS CEDEX 07",
    "privacy.cnilPhone": "Phone: 01 53 73 22 22",
    "privacy.cnilWebsite": "Website:",
    "privacy.modifications": "Modifications",
    "privacy.modificationsText": "We reserve the right to modify this privacy policy at any time. The current version is always available on our website.",
    
    // Cookie Policy
    "cookies.title": "Cookie Policy",
    "cookies.what": "What is a cookie?",
    "cookies.whatText": "A cookie is a small text file placed on your device (computer, tablet, smartphone) when visiting a website. It allows the website to remember information about your visit, such as your preferred language and other settings, to make your next visit easier and make the site more useful.",
    "cookies.which": "Which cookies do we use?",
    "cookies.necessary": "Strictly Necessary Cookies",
    "cookies.necessaryText": "These cookies are essential for the proper functioning of the website. They allow you to navigate the site and use its features.",
    "cookies.duration": "Duration:",
    "cookies.session": "Session",
    "cookies.consentRequired": "Consent required:",
    "cookies.no": "No",
    "cookies.yes": "Yes",
    "cookies.analytical": "Analytical Cookies",
    "cookies.analyticalText": "These cookies allow us to measure our website's audience and analyze how visitors use our site. This information helps us improve content and user experience.",
    "cookies.analyticalDuration": "Maximum 13 months",
    "cookies.examples": "Examples:",
    "cookies.analyticalExample": "Google Analytics (anonymized)",
    "cookies.functional": "Functionality Cookies",
    "cookies.functionalText": "These cookies allow us to remember your preferences (language, region, layout) and personalize your experience on the site.",
    "cookies.functionalDuration": "Variable (up to 12 months)",
    "cookies.advertising": "Advertising Cookies",
    "cookies.advertisingText": "We do not currently use advertising or targeting cookies on our site.",
    "cookies.advertisingConsent": "Yes (if used in the future)",
    "cookies.management": "Managing Your Cookies",
    "cookies.managementText": "You can choose to disable these cookies at any time. Your browser can also be set to notify you when cookies are placed on your device and ask you to accept or refuse them.",
    "cookies.browser": "On Your Browser",
    "cookies.browserText": "You can configure your browser to block cookies:",
    "cookies.chrome": "Chrome:",
    "cookies.chromeText": "Settings → Privacy and security → Cookies",
    "cookies.firefox": "Firefox:",
    "cookies.firefoxText": "Options → Privacy and security → Cookies and site data",
    "cookies.safari": "Safari:",
    "cookies.safariText": "Preferences → Privacy → Cookies and website data",
    "cookies.edge": "Edge:",
    "cookies.edgeText": "Settings → Privacy and services → Cookies",
    "cookies.consequences": "Consequences of Refusing Cookies",
    "cookies.consequencesText": "Refusing certain cookies may impact your browsing experience and limit access to certain website features. Strictly necessary cookies cannot be disabled.",
    "cookies.thirdParty": "Third-Party Services",
    "cookies.thirdPartyText": "We may use third-party services that place their own cookies:",
    "cookies.google": "Google Analytics:",
    "cookies.googleText": "Anonymized audience measurement",
    "cookies.videos": "YouTube/Vimeo videos:",
    "cookies.videosText": "If video content is embedded",
    "cookies.thirdPartyPolicies": "These services have their own privacy and cookie policies.",
    "cookies.personalData": "Cookies and Personal Data",
    "cookies.personalDataText": "Cookies may contain personal data. To learn more about how we process your personal data, see our",
    "cookies.privacyPolicyLink": "Privacy Policy",
    "cookies.updates": "Cookie Policy Updates",
    "cookies.updatesText": "We may update this cookie policy to reflect changes in technologies used or legislative developments. We encourage you to regularly consult this page.",
    "cookies.contact": "Contact",
    "cookies.contactText": "For any questions regarding our use of cookies, you can contact us:",
    
    // Terms of Service
    "terms.title": "Terms of Service",
    "terms.object": "1. Object",
    "terms.objectText": "These Terms of Service (ToS) define the terms and conditions of use of the services offered by BerinIA, as well as the rights and obligations of the parties in this context.",
    "terms.legal": "2. Legal Mentions",
    "terms.legalText1": "The website berinia.com is published by BerinIA, SAS with a capital of €10,000, registered with the RCS of [City] under number [RCS Number].",
    "terms.legalText2": "Headquarters:",
    "terms.legalText3": "[Address]",
    "terms.access": "3. Service Access",
    "terms.accessText1": "The BerinIA service is accessible to any natural or legal person with Internet access. Use of the service requires the conclusion of a service contract.",
    "terms.accessText2": "BerinIA reserves the right to refuse access to the service, unilaterally and without prior notice, to any user not respecting these ToS.",
    "terms.description": "4. Service Description",
    "terms.descriptionText": "BerinIA provides an intelligent telephony solution based on artificial intelligence including:",
    "terms.feature1": "Automated inbound and outbound call management",
    "terms.feature2": "Speech recognition and synthesis (ASR/TTS)",
    "terms.feature3": "Intelligent call routing",
    "terms.feature4": "Dashboards and analytics",
    "terms.feature5": "Integrations with third-party systems",
    "terms.feature6": "Customization of scripts and scenarios",
    "terms.obligations": "5. User Obligations",
    "terms.obligationsText": "The user agrees to:",
    "terms.obligation1": "Provide accurate and up-to-date information",
    "terms.obligation2": "Use the service in accordance with applicable laws",
    "terms.obligation3": "Not use the service for illegal or fraudulent purposes",
    "terms.obligation4": "Respect BerinIA's intellectual property rights",
    "terms.obligation5": "Maintain the confidentiality of their access credentials",
    "terms.obligation6": "Immediately inform BerinIA of any unauthorized use",
    "terms.pricing": "6. Pricing",
    "terms.pricingText1": "BerinIA service rates are indicated in euros excluding tax. They are available upon request or in commercial offers sent to customers.",
    "terms.pricingText2": "BerinIA reserves the right to modify its rates at any time. New rates will apply to new contracts and renewals, with 30 days' notice.",
    "terms.ip": "7. Intellectual Property",
    "terms.ipText1": "All elements of the BerinIA service (software, texts, images, sounds, videos, databases, etc.) are protected by intellectual property law.",
    "terms.ipText2": "Any reproduction, representation, modification, publication, adaptation of all or part of the service elements, whatever the means or process used, is prohibited, except with prior written authorization from BerinIA.",
    "terms.data": "8. Personal Data",
    "terms.dataText1": "BerinIA undertakes to comply with the applicable regulations regarding the processing of personal data and, in particular, the GDPR.",
    "terms.dataText2": "For more information on the processing of your personal data, please consult our",
    "terms.privacyPolicyLink": "Privacy Policy",
    "terms.availability": "9. Availability and Maintenance",
    "terms.availabilityText1": "BerinIA strives to ensure optimal service availability 24/7. However, BerinIA cannot guarantee absolute availability and reserves the right to temporarily interrupt access to the service for maintenance or update reasons.",
    "terms.availabilityText2": "A monthly availability rate is guaranteed according to the terms of the service contract (SLA).",
    "terms.liability": "10. Liability",
    "terms.liabilityText1": "BerinIA undertakes to provide its services with diligence and according to the rules of the art. BerinIA's liability can only be engaged in case of proven fault or negligence.",
    "terms.liabilityText2": "BerinIA cannot be held responsible for indirect damages such as loss of revenue, customers, data or business opportunities.",
    "terms.termination": "11. Termination",
    "terms.terminationText1": "The contract may be terminated by either party according to the terms provided in the service contract, respecting a notice period of [X] months.",
    "terms.terminationText2": "In case of serious breach of contractual obligations, BerinIA reserves the right to suspend or immediately terminate access to the service.",
    "terms.forceMajeure": "12. Force Majeure",
    "terms.forceMajeureText": "BerinIA cannot be held responsible for the non-performance of its obligations in case of force majeure as defined by French case law.",
    "terms.modifications": "13. ToS Modifications",
    "terms.modificationsText1": "BerinIA reserves the right to modify these ToS at any time. Users will be informed of any modification by email or via the website.",
    "terms.modificationsText2": "Continued use of the service after notification constitutes acceptance of the new ToS.",
    "terms.law": "14. Applicable Law and Jurisdiction",
    "terms.lawText": "These ToS are governed by French law. In case of dispute, and failing an amicable agreement, the French courts shall have sole jurisdiction.",
    "terms.contact": "15. Contact",
    "terms.contactText": "For any questions regarding these ToS, you can contact us:",
    "terms.contactMail": "Mail:",
  },
  fr: {
    // Header
    "header.product": "Produit",
    "header.features": "Fonctionnalités",
    "header.cases": "Cas clients",
    "header.contact": "Contact",
    "header.cta": "Demander une démo",
    
    // Hero
    "hero.title": "Transformez Votre Service Client avec l'IA",
    "hero.subtitle": "Automatisez vos appels téléphoniques avec une IA ultra-réaliste qui gère vos demandes clients 24/7",
    "hero.cta": "Essayer Gratuitement",
    "hero.demo": "Voir la démo interactive",
    "hero.badge1": "Déploiement 48h",
    "hero.badge2": "Fiable 24/7",
    "hero.badge3": "100% Personnalisable",
    "hero.activeCall": "Appel IA actif",
    "hero.accuracy": "97% précision • Temps réel",
    
    // Product
    "product.title": "Ce que fait BerinIA",
    "product.subtitle": "Plateforme d'IA conversationnelle qui transforme votre téléphonie en machine à convertir",
    "product.feature1.title": "Réponse automatique intelligente",
    "product.feature1.description": "Vos clients obtiennent des réponses instantanées, naturelles et contextualisées à toute heure.",
    "product.feature2.title": "Appels entrants & sortants",
    "product.feature2.description": "Gérez la réception d'appels et lancez des campagnes proactives avec la même intelligence.",
    "product.feature3.title": "Intégration métier",
    "product.feature3.description": "Connecté à vos outils CRM, agenda et systèmes métier pour une expérience fluide.",
    "product.discover": "Découvrir",
    
    // Features
    "features.title": "Fonctionnalités nouvelle génération",
    "features.subtitle": "Technologies d'IA conversationnelle qui transforment chaque interaction en opportunité",
    "features.feature1.title": "Reconnaissance vocale avancée (ASR)",
    "features.feature1.description": "Transcription en temps réel avec précision métier et compréhension contextuelle avancée",
    "features.feature1.stat": "-30%",
    "features.feature1.label": "temps d'attente",
    "features.feature2.title": "Synthèse vocale naturelle (TTS)",
    "features.feature2.description": "Voix personnalisables ultra-réalistes, ton adapté à votre marque et secteur",
    "features.feature2.stat": "+45%",
    "features.feature2.label": "satisfaction client",
    "features.feature3.title": "Routage intelligent d'appels",
    "features.feature3.description": "Transfert automatique vers le bon service ou agent avec contexte préservé",
    "features.feature3.stat": "95%",
    "features.feature3.label": "résolution au 1er appel",
    "features.feature4.title": "Analytics et insights IA",
    "features.feature4.description": "Tableaux de bord en temps réel, tendances prédictives et recommandations",
    "features.feature4.stat": "+60%",
    "features.feature4.label": "performance commerciale",
    "features.feature5.title": "Scripts dynamiques intelligents",
    "features.feature5.description": "Adaptez les dialogues en temps réel selon le contexte et comportement client",
    "features.feature5.stat": "48h",
    "features.feature5.label": "déployé",
    "features.badge1": "Temps réel",
    "features.badge2": "Personnalisable",
    "features.badge3": "Scalable",
    
    // Social Proof
    "social.title": "Ils nous font confiance",
    "social.subtitle": "Des résultats mesurables dès les premières semaines",
    "social.stat1.value": "50 000+",
    "social.stat1.label": "Appels gérés par mois",
    "social.stat2.value": "30",
    "social.stat2.label": "Minutes gagnées par jour",
    "social.stat3.value": "45%",
    "social.stat3.label": "Taux de conversion",
    "social.testimonial1.content": "Depuis BerinIA, nous ne ratons plus aucun appel. +40% de prises de rendez-vous en 3 mois. L'IA comprend parfaitement le contexte immobilier.",
    "social.testimonial1.name": "Marie Dubois",
    "social.testimonial1.role": "Directrice Commerciale",
    "social.testimonial1.company": "Immo+",
    "social.testimonial2.content": "L'IA gère parfaitement les demandes courantes. Mon équipe se concentre sur les dossiers complexes. ROI positif dès le 2e mois.",
    "social.testimonial2.name": "Thomas Bernard",
    "social.testimonial2.role": "Gérant",
    "social.testimonial2.company": "Services Pro",
    "social.testimonial3.content": "Installation rapide, formation claire. Les clients apprécient la réactivité 24/7. Meilleur investissement de l'année.",
    "social.testimonial3.name": "Sophie Martin",
    "social.testimonial3.role": "Responsable Client",
    "social.testimonial3.company": "TechServices",
    "social.trust1.label": "Disponibilité",
    "social.trust1.value": "99.9%",
    "social.trust2.label": "Conformité RGPD",
    "social.trust3.label": "Support 24/7",
    "social.trust4.label": "Sécurité ISO",
    
    // FAQ
    "faq.title": "Questions fréquentes",
    "faq.subtitle": "Tout ce que vous devez savoir sur BerinIA",
    "faq.q1": "Combien de temps faut-il pour déployer BerinIA ?",
    "faq.a1": "Le déploiement initial prend entre 48h et 5 jours selon la complexité de vos scénarios. Nous gérons l'intégration technique et la personnalisation de l'IA pour votre secteur.",
    "faq.q2": "L'IA peut-elle vraiment remplacer un humain ?",
    "faq.a2": "BerinIA gère efficacement les demandes courantes et répétitives (80% des appels). Pour les cas complexes, l'appel est transféré intelligemment à un agent humain avec tout le contexte.",
    "faq.q3": "Comment se passe l'intégration avec notre CRM ?",
    "faq.a3": "Nous proposons des connecteurs natifs pour Salesforce, HubSpot, Pipedrive et d'autres outils. Les API ouvertes permettent aussi des intégrations sur mesure rapides.",
    "faq.q4": "Quelles sont les options de tarification ?",
    "faq.a4": "Nous proposons un modèle par usage (coût par appel) ou forfait mensuel selon votre volume. Contactez-nous pour un devis personnalisé adapté à vos besoins spécifiques.",
    "faq.q5": "Les données sont-elles sécurisées et conformes RGPD ?",
    "faq.a5": "Absolument. BerinIA est hébergé en Europe, conforme RGPD, et certifié ISO 27001. Vos données client restent privées, chiffrées et ne sont jamais partagées.",
    "faq.q6": "Peut-on personnaliser la voix et le ton de l'IA ?",
    "faq.a6": "Oui, entièrement. Vous choisissez la voix, le vocabulaire, le niveau de formalité et les scripts selon votre image de marque et secteur d'activité. Démos disponibles.",
    "faq.noAnswer": "Vous ne trouvez pas la réponse à votre question ?",
    "faq.contact": "Contactez notre équipe",
    
    // Contact
    "contact.title": "Prêt à Transformer Votre Service Client ?",
    "contact.subtitle": "Contactez-nous pour une démo personnalisée",
    "contact.name": "Nom complet",
    "contact.email": "Email professionnel",
    "contact.phone": "Numéro de téléphone",
    "contact.company": "Entreprise",
    "contact.message": "Votre message",
    "contact.send": "Envoyer la demande",
    "contact.success": "Message envoyé avec succès !",
    "contact.error": "Erreur lors de l'envoi",
    "contact.ourDetails": "Nos coordonnées",
    "contact.emailLabel": "Email",
    "contact.phoneLabel": "Téléphone",
    "contact.hoursLabel": "Horaires",
    "contact.schedule": "Lun - Ven : 9h - 18h\nSam : 9h - 12h",
    "contact.dataSecurityTitle": "Vos données en sécurité",
    "contact.dataSecurityText": "Nous respectons votre vie privée. Aucune donnée n'est vendue à des tiers. Conformité RGPD garantie, hébergement Europe, chiffrement de bout en bout.",
    
    // Footer
    "footer.product": "Produit",
    "footer.features": "Fonctionnalités",
    "footer.pricing": "Tarifs",
    "footer.company": "Entreprise",
    "footer.about": "À propos",
    "footer.blog": "Blog",
    "footer.careers": "Carrières",
    "footer.legal": "Légal",
    "footer.privacy": "Politique de confidentialité",
    "footer.terms": "Conditions d'utilisation",
    "footer.cookies": "Politique des cookies",
    "footer.notice": "Mentions légales",
    "footer.rights": "Tous droits réservés",
    
    // Test Page
    "test.title": "Testez Notre IA Gratuitement",
    "test.subtitle": "Entrez vos informations et notre IA vous appellera immédiatement pour une démonstration en direct",
    "test.phone": "Numéro de téléphone",
    "test.phonePlaceholder": "+33 6 12 34 56 78",
    "test.sector": "Secteur d'activité",
    "test.sectorPlaceholder": "E-commerce, Immobilier, Services...",
    "test.company": "Nom de l'entreprise",
    "test.companyPlaceholder": "Votre entreprise",
    "test.email": "Email professionnel",
    "test.emailPlaceholder": "contact@entreprise.com",
    "test.consent": "J'accepte d'être contacté pour une démonstration du produit",
    "test.gdpr": "J'accepte le traitement de mes données personnelles conformément au RGPD",
    "test.terms": "J'accepte les conditions générales d'utilisation",
    "test.submit": "Lancer l'appel de démo",
    "test.submitting": "Lancement de l'appel...",
    "test.success": "Succès ! Vous allez recevoir un appel dans quelques instants",
    "test.error": "Une erreur est survenue. Veuillez réessayer.",
    "test.checkboxError": "Veuillez accepter toutes les conditions requises",
    
    // Not Found
    "notfound.title": "404",
    "notfound.message": "Oups ! Page introuvable",
    "notfound.home": "Retour à l'accueil",
    
    // Legal Pages Common
    "legal.backHome": "Retour à l'accueil",
    "legal.lastUpdate": "Dernière mise à jour :",
    
    // Legal Notice
    "legal.notice.title": "Mentions Légales",
    "legal.notice.editor": "Éditeur du site",
    "legal.notice.companyName": "Raison sociale :",
    "legal.notice.legalForm": "Forme juridique :",
    "legal.notice.capital": "Capital social :",
    "legal.notice.headquarters": "Siège social :",
    "legal.notice.rcs": "RCS :",
    "legal.notice.siret": "SIRET :",
    "legal.notice.vat": "TVA intracommunautaire :",
    "legal.notice.email": "Email :",
    "legal.notice.phone": "Téléphone :",
    "legal.notice.director": "Directeur de publication",
    "legal.notice.directorName": "[Nom du directeur de publication]",
    "legal.notice.hosting": "Hébergement",
    "legal.notice.hostedBy": "Le site est hébergé par :",
    "legal.notice.hostName": "Raison sociale :",
    "legal.notice.hostAddress": "Adresse :",
    "legal.notice.hostPhone": "Téléphone :",
    "legal.notice.ip": "Propriété intellectuelle",
    "legal.notice.ipText1": "L'ensemble de ce site relève de la législation française et internationale sur le droit d'auteur et la propriété intellectuelle. Tous les droits de reproduction sont réservés, y compris pour les documents téléchargeables et les représentations iconographiques et photographiques.",
    "legal.notice.ipText2": "La reproduction de tout ou partie de ce site sur un support électronique quel qu'il soit est formellement interdite sauf autorisation expresse du directeur de la publication.",
    "legal.notice.gdpr": "Protection des données personnelles",
    "legal.notice.gdprText1": "Conformément à la loi « Informatique et Libertés » du 6 janvier 1978 modifiée et au Règlement Général sur la Protection des Données (RGPD), vous disposez d'un droit d'accès, de rectification, de suppression et d'opposition aux données personnelles vous concernant.",
    "legal.notice.gdprText2": "Pour exercer ces droits, vous pouvez nous contacter à l'adresse : contact@berinia.com",
    "legal.notice.cookies": "Cookies",
    "legal.notice.cookiesText1": "Le site peut être amené à vous demander l'acceptation des cookies pour des besoins de statistiques et d'affichage. Un cookie est une information déposée sur votre disque dur par le serveur du site que vous visitez.",
    "legal.notice.cookiesText2": "Vous pouvez désactiver les cookies dans les paramètres de votre navigateur.",
    "legal.notice.links": "Liens hypertextes",
    "legal.notice.linksText": "Le site peut contenir des liens hypertextes vers d'autres sites. BerinIA n'exerce aucun contrôle sur ces sites et décline toute responsabilité quant à leur contenu.",
    "legal.notice.law": "Loi applicable",
    "legal.notice.lawText": "Les présentes mentions légales sont régies par le droit français. En cas de litige, les tribunaux français seront seuls compétents.",
    
    // Privacy Policy
    "privacy.title": "Politique de Confidentialité",
    "privacy.intro": "Introduction",
    "privacy.introText": "BerinIA accorde une grande importance à la protection de vos données personnelles. Cette politique de confidentialité vous informe sur la manière dont nous collectons, utilisons et protégeons vos informations personnelles conformément au Règlement Général sur la Protection des Données (RGPD).",
    "privacy.controller": "Responsable du traitement",
    "privacy.controllerText": "Le responsable du traitement des données est :",
    "privacy.controllerName": "BerinIA",
    "privacy.dataCollected": "Données collectées",
    "privacy.dataCollectedText": "Nous collectons les données personnelles suivantes :",
    "privacy.dataItem1": "Nom et prénom",
    "privacy.dataItem2": "Adresse email professionnelle",
    "privacy.dataItem3": "Numéro de téléphone",
    "privacy.dataItem4": "Nom de la société",
    "privacy.dataItem5": "Messages et informations que vous nous transmettez",
    "privacy.dataItem6": "Données de navigation (cookies, adresse IP, navigateur)",
    "privacy.purposes": "Finalités du traitement",
    "privacy.purposesText": "Vos données sont collectées pour les finalités suivantes :",
    "privacy.purpose1": "Répondre à vos demandes de contact et de démonstration",
    "privacy.purpose2": "Gérer la relation client et le service après-vente",
    "privacy.purpose3": "Améliorer nos services et notre site web",
    "privacy.purpose4": "Vous envoyer des informations commerciales (avec votre consentement)",
    "privacy.purpose5": "Respecter nos obligations légales et réglementaires",
    "privacy.legalBasis": "Base légale",
    "privacy.legalBasisText": "Le traitement de vos données repose sur :",
    "privacy.basis1": "Votre consentement explicite",
    "privacy.basis2": "L'exécution d'un contrat ou de mesures précontractuelles",
    "privacy.basis3": "Notre intérêt légitime à améliorer nos services",
    "privacy.basis4": "Le respect de nos obligations légales",
    "privacy.recipients": "Destinataires des données",
    "privacy.recipientsText1": "Vos données personnelles sont destinées aux services internes de BerinIA. Elles peuvent également être transmises à nos sous-traitants techniques (hébergement, email) qui agissent uniquement sur nos instructions.",
    "privacy.recipientsText2": "Vos données ne sont jamais vendues à des tiers.",
    "privacy.retention": "Durée de conservation",
    "privacy.retentionText": "Vos données sont conservées pendant :",
    "privacy.retention1": "3 ans pour les prospects à compter du dernier contact",
    "privacy.retention2": "Durée de la relation contractuelle + 5 ans pour les clients",
    "privacy.retention3": "13 mois maximum pour les cookies de mesure d'audience",
    "privacy.rights": "Vos droits",
    "privacy.rightsText": "Conformément au RGPD, vous disposez des droits suivants :",
    "privacy.right1": "Droit d'accès :",
    "privacy.right1Text": "obtenir une copie de vos données",
    "privacy.right2": "Droit de rectification :",
    "privacy.right2Text": "corriger vos données inexactes",
    "privacy.right3": "Droit à l'effacement :",
    "privacy.right3Text": "supprimer vos données",
    "privacy.right4": "Droit à la limitation :",
    "privacy.right4Text": "limiter le traitement de vos données",
    "privacy.right5": "Droit d'opposition :",
    "privacy.right5Text": "vous opposer au traitement de vos données",
    "privacy.right6": "Droit à la portabilité :",
    "privacy.right6Text": "récupérer vos données dans un format structuré",
    "privacy.rightsContact": "Pour exercer ces droits, contactez-nous à : contact@berinia.com",
    "privacy.security": "Sécurité",
    "privacy.securityText1": "Nous mettons en œuvre toutes les mesures techniques et organisationnelles appropriées pour protéger vos données contre la perte, l'utilisation abusive, l'accès non autorisé, la divulgation, l'altération ou la destruction.",
    "privacy.securityText2": "Nos serveurs sont hébergés en Europe et bénéficient d'un chiffrement de bout en bout.",
    "privacy.cookies": "Cookies",
    "privacy.cookiesText": "Notre site utilise des cookies pour améliorer votre expérience de navigation et mesurer l'audience. Vous pouvez gérer vos préférences de cookies dans les paramètres de votre navigateur.",
    "privacy.complaint": "Réclamation",
    "privacy.complaintText": "Si vous estimez que vos droits ne sont pas respectés, vous pouvez introduire une réclamation auprès de la CNIL :",
    "privacy.cnilAddress": "CNIL - 3 Place de Fontenoy - TSA 80715 - 75334 PARIS CEDEX 07",
    "privacy.cnilPhone": "Téléphone : 01 53 73 22 22",
    "privacy.cnilWebsite": "Site web :",
    "privacy.modifications": "Modifications",
    "privacy.modificationsText": "Nous nous réservons le droit de modifier cette politique de confidentialité à tout moment. La version en vigueur est toujours accessible sur notre site web.",
    
    // Cookie Policy
    "cookies.title": "Politique de Cookies",
    "cookies.what": "Qu'est-ce qu'un cookie ?",
    "cookies.whatText": "Un cookie est un petit fichier texte déposé sur votre terminal (ordinateur, tablette, smartphone) lors de la visite d'un site web. Il permet au site de mémoriser des informations sur votre visite, comme votre langue préférée et d'autres paramètres, afin de faciliter votre prochaine visite et de rendre le site plus utile.",
    "cookies.which": "Quels cookies utilisons-nous ?",
    "cookies.necessary": "🔧 Cookies strictement nécessaires",
    "cookies.necessaryText": "Ces cookies sont indispensables au bon fonctionnement du site. Ils vous permettent de naviguer sur le site et d'utiliser ses fonctionnalités.",
    "cookies.duration": "Durée :",
    "cookies.session": "Session",
    "cookies.consentRequired": "Consentement requis :",
    "cookies.no": "Non",
    "cookies.yes": "Oui",
    "cookies.analytical": "📊 Cookies analytiques",
    "cookies.analyticalText": "Ces cookies nous permettent de mesurer l'audience de notre site et d'analyser la façon dont les visiteurs utilisent notre site. Ces informations nous aident à améliorer le contenu et l'expérience utilisateur.",
    "cookies.analyticalDuration": "13 mois maximum",
    "cookies.examples": "Exemples :",
    "cookies.analyticalExample": "Google Analytics (anonymisé)",
    "cookies.functional": "⚙️ Cookies de fonctionnalité",
    "cookies.functionalText": "Ces cookies permettent de mémoriser vos préférences (langue, région, mise en page) et de personnaliser votre expérience sur le site.",
    "cookies.functionalDuration": "Variable (jusqu'à 12 mois)",
    "cookies.advertising": "🎯 Cookies publicitaires",
    "cookies.advertisingText": "Actuellement, nous n'utilisons pas de cookies publicitaires ou de ciblage sur notre site.",
    "cookies.advertisingConsent": "Oui (si utilisés à l'avenir)",
    "cookies.management": "Gestion de vos cookies",
    "cookies.managementText": "Vous pouvez à tout moment choisir de désactiver ces cookies. Votre navigateur peut également être paramétré pour vous signaler les cookies qui sont déposés dans votre terminal et vous demander de les accepter ou non.",
    "cookies.browser": "🌐 Sur votre navigateur",
    "cookies.browserText": "Vous pouvez configurer votre navigateur pour bloquer les cookies :",
    "cookies.chrome": "Chrome :",
    "cookies.chromeText": "Paramètres → Confidentialité et sécurité → Cookies",
    "cookies.firefox": "Firefox :",
    "cookies.firefoxText": "Options → Vie privée et sécurité → Cookies et données de sites",
    "cookies.safari": "Safari :",
    "cookies.safariText": "Préférences → Confidentialité → Cookies et données de sites web",
    "cookies.edge": "Edge :",
    "cookies.edgeText": "Paramètres → Confidentialité et services → Cookies",
    "cookies.consequences": "⚠️ Conséquences du refus des cookies",
    "cookies.consequencesText": "Le refus de certains cookies peut avoir un impact sur votre expérience de navigation et limiter l'accès à certaines fonctionnalités du site. Les cookies strictement nécessaires ne peuvent pas être désactivés.",
    "cookies.thirdParty": "Services tiers",
    "cookies.thirdPartyText": "Nous pouvons utiliser des services tiers qui déposent leurs propres cookies :",
    "cookies.google": "Google Analytics :",
    "cookies.googleText": "Mesure d'audience anonymisée",
    "cookies.videos": "Vidéos YouTube/Vimeo :",
    "cookies.videosText": "Si du contenu vidéo est intégré",
    "cookies.thirdPartyPolicies": "Ces services ont leurs propres politiques de confidentialité et de cookies.",
    "cookies.personalData": "Cookies et données personnelles",
    "cookies.personalDataText": "Les cookies peuvent contenir des données personnelles. Pour en savoir plus sur la façon dont nous traitons vos données personnelles, consultez notre",
    "cookies.privacyPolicyLink": "Politique de Confidentialité",
    "cookies.updates": "Mise à jour de la politique de cookies",
    "cookies.updatesText": "Nous pouvons être amenés à modifier cette politique de cookies pour refléter les changements dans les technologies utilisées ou les évolutions législatives. Nous vous encourageons à consulter régulièrement cette page.",
    "cookies.contact": "Contact",
    "cookies.contactText": "Pour toute question concernant notre utilisation des cookies, vous pouvez nous contacter :",
    
    // Terms of Service
    "terms.title": "Conditions Générales d'Utilisation",
    "terms.object": "1. Objet",
    "terms.objectText": "Les présentes Conditions Générales d'Utilisation (CGU) ont pour objet de définir les modalités et conditions d'utilisation des services proposés par BerinIA, ainsi que de définir les droits et obligations des parties dans ce cadre.",
    "terms.legal": "2. Mentions légales",
    "terms.legalText1": "Le site berinia.com est édité par BerinIA, SAS au capital de 10 000 €, immatriculée au RCS de [Ville] sous le numéro [Numéro RCS].",
    "terms.legalText2": "Siège social :",
    "terms.legalText3": "[Adresse]",
    "terms.access": "3. Accès au service",
    "terms.accessText1": "Le service BerinIA est accessible à toute personne physique ou morale disposant d'un accès à Internet. L'utilisation du service nécessite la conclusion d'un contrat de prestation de services.",
    "terms.accessText2": "BerinIA se réserve le droit de refuser l'accès au service, unilatéralement et sans notification préalable, à tout utilisateur ne respectant pas les présentes CGU.",
    "terms.description": "4. Description du service",
    "terms.descriptionText": "BerinIA fournit une solution de téléphonie intelligente basée sur l'intelligence artificielle comprenant :",
    "terms.feature1": "Gestion automatisée des appels entrants et sortants",
    "terms.feature2": "Reconnaissance et synthèse vocale (ASR/TTS)",
    "terms.feature3": "Routage intelligent des appels",
    "terms.feature4": "Tableaux de bord et analytics",
    "terms.feature5": "Intégrations avec systèmes tiers",
    "terms.feature6": "Personnalisation des scripts et scénarios",
    "terms.obligations": "5. Obligations de l'utilisateur",
    "terms.obligationsText": "L'utilisateur s'engage à :",
    "terms.obligation1": "Fournir des informations exactes et à jour",
    "terms.obligation2": "Utiliser le service conformément aux lois en vigueur",
    "terms.obligation3": "Ne pas utiliser le service à des fins illégales ou frauduleuses",
    "terms.obligation4": "Respecter les droits de propriété intellectuelle de BerinIA",
    "terms.obligation5": "Maintenir la confidentialité de ses identifiants d'accès",
    "terms.obligation6": "Informer immédiatement BerinIA de tout usage non autorisé",
    "terms.pricing": "6. Tarification",
    "terms.pricingText1": "Les tarifs des services BerinIA sont indiqués en euros hors taxes. Ils sont disponibles sur demande ou dans les offres commerciales transmises aux clients.",
    "terms.pricingText2": "BerinIA se réserve le droit de modifier ses tarifs à tout moment. Les nouveaux tarifs seront applicables aux nouveaux contrats et aux renouvellements, moyennant un préavis de 30 jours.",
    "terms.ip": "7. Propriété intellectuelle",
    "terms.ipText1": "Tous les éléments du service BerinIA (logiciels, textes, images, sons, vidéos, bases de données, etc.) sont protégés par le droit de la propriété intellectuelle.",
    "terms.ipText2": "Toute reproduction, représentation, modification, publication, adaptation de tout ou partie des éléments du service, quel que soit le moyen ou le procédé utilisé, est interdite, sauf autorisation écrite préalable de BerinIA.",
    "terms.data": "8. Données personnelles",
    "terms.dataText1": "BerinIA s'engage à respecter la réglementation en vigueur applicable au traitement des données personnelles et, en particulier, le RGPD.",
    "terms.dataText2": "Pour plus d'informations sur le traitement de vos données personnelles, veuillez consulter notre",
    "terms.privacyPolicyLink": "Politique de Confidentialité",
    "terms.availability": "9. Disponibilité et maintenance",
    "terms.availabilityText1": "BerinIA s'efforce d'assurer une disponibilité optimale du service 24h/24, 7j/7. Toutefois, BerinIA ne peut garantir une disponibilité absolue et se réserve le droit d'interrompre temporairement l'accès au service pour des raisons de maintenance ou de mise à jour.",
    "terms.availabilityText2": "Un taux de disponibilité mensuel est garanti selon les termes du contrat de service (SLA).",
    "terms.liability": "10. Responsabilité",
    "terms.liabilityText1": "BerinIA s'engage à fournir ses services avec diligence et selon les règles de l'art. La responsabilité de BerinIA ne peut être engagée qu'en cas de faute ou de négligence prouvée.",
    "terms.liabilityText2": "BerinIA ne saurait être tenue responsable des dommages indirects tels que la perte de chiffre d'affaires, de clientèle, de données ou d'opportunités commerciales.",
    "terms.termination": "11. Résiliation",
    "terms.terminationText1": "Le contrat peut être résilié par l'une ou l'autre des parties selon les modalités prévues au contrat de prestation de services, en respectant un préavis de [X] mois.",
    "terms.terminationText2": "En cas de manquement grave aux obligations contractuelles, BerinIA se réserve le droit de suspendre ou résilier immédiatement l'accès au service.",
    "terms.forceMajeure": "12. Force majeure",
    "terms.forceMajeureText": "BerinIA ne pourra être tenue responsable de l'inexécution de ses obligations en cas de force majeure telle que définie par la jurisprudence française.",
    "terms.modifications": "13. Modification des CGU",
    "terms.modificationsText1": "BerinIA se réserve le droit de modifier les présentes CGU à tout moment. Les utilisateurs seront informés de toute modification par email ou via le site web.",
    "terms.modificationsText2": "La poursuite de l'utilisation du service après notification vaut acceptation des nouvelles CGU.",
    "terms.law": "14. Droit applicable et juridiction",
    "terms.lawText": "Les présentes CGU sont régies par le droit français. En cas de litige, et à défaut d'accord amiable, les tribunaux français seront seuls compétents.",
    "terms.contact": "15. Contact",
    "terms.contactText": "Pour toute question relative aux présentes CGU, vous pouvez nous contacter :",
    "terms.contactMail": "Courrier :",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  useEffect(() => {
    const savedLang = localStorage.getItem("language") as Language;
    if (savedLang && (savedLang === "en" || savedLang === "fr")) {
      setLanguage(savedLang);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
